### ISSUE TITLE
Fix `{%` and `{{` 🌈 colors

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/nunjucks.novaextension#1]
### Description

Brackets are displayed in a lot of color and are not really readable

### Ask

Fix the color so that every Nunjucks brackets are the same color

### Additional Info

- ![CleanShot 2020-12-02 at 11 08 55](https://user-images.githubusercontent.com/611234/100858846-cc266200-348e-11eb-8190-1f945a492904.png)
- https://devforum.nova.app/t/disabling-rainbow-brackets/508

**Comment by alienlebarge** [comment]
So it commes from this config
![CleanShot 2020-12-02 at 11 12 32](https://user-images.githubusercontent.com/611234/100859278-553d9900-348f-11eb-82ad-7cdb69858a9a.png)

**Comment by armstrongb** [comment]
Thanks for the work on this njk syntax highlighter 🙌 . 

I came to raise an issue about the 🌈 syntax problem but you have already got an issue to address it 👍 

Merci

**Comment by alienlebarge** [comment]
It has been fixed in 10846c3
